version: '3.7'
services:
  jetlar:
    build:    
      context: .
    image: jetlar:latest
    container_name: jetlar
    hostname: jetlar
    restart: unless-stopped
    tty: true
    environment:
      - USER_ID=${USER_ID:-0}
      - DB_CONNECTION=mysql
      - DB_HOST=jetlar-db
      - DB_PORT=3310
      - DB_DATABASE=jetlar
      - DB_USERNAME=jetlar
      - DB_PASSWORD=00000000
    working_dir: /var/www/app
    ports:
      - '83:80'
    volumes:
      - ./src:/var/www/app
    networks:
      - netdocker  
  jetlar-phpmyadmin:
    image: phpmyadmin:latest
    container_name: jetlar-phpmyadmin
    restart: unless-stopped
    tty: true
    environment:
      - PMA_HOST=jetlar-db
      - PMA_PORT=3310
      - PMA_USER=jetlar
      - PMA_PASSWORD=00000000
    ports:
      - '89:80'
    networks:
      - netdocker
  jetlar-db:
    image: mariadb:latest
    container_name: jetlar-db
    hostname: jetlar-db
    restart: unless-stopped
    tty: true
    environment:
      - MARIADB_DATABASE=jetlar
      - MARIADB_USER=jetlar
      - MARIADB_PASSWORD=00000000
      - MARIADB_ROOT_PASSWORD=00000000
    command: --port=3310 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3310:3310'
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - netdocker
networks:
  netdocker:
    driver: bridge